### ISSUE TITLE
Support "python" key

### ISSUE THREAD

**Issue by seanbudd** [pre-commit-ci/pre-commit-ci-config#133]
Using the [python key](https://pre-commit.com/#overriding-language-version) for local checks logs a warning but doesn't fail

```log
[WARNING] Unexpected key(s) present on local => unitTest: python
[INFO] Initializing environment for local:licensecheck.
[WARNING] Unexpected key(s) present on local => licenseCheck: python
```

**Comment by asottile** [comment]
where do you see `python` as a supported key?  read the link you posted
